site_name: Notification Server
site_url: https://sjohnsonaz.github.io/notification-server
repo_url: https://github.com/sjohnsonaz/notification-server
copyright: Copyright &copy; 2017 Sean Johnson
pages:
    - Home: index.md
theme: readthedocs